export interface Shipment {
  id: string;
  nroTramite: number;
  fechaTramite: string;
  nroCote: string;
  nombreMedicoVeterinario?: string | null;
  nombreEstablecimientoCertif?: string | null;
  nombreEstablecimientoProd?: string | null;
  nroEstablecimientoProd?: number | null;
  fechaEmitidoCote?: string | null;
  temperaturaC?: number | null;
  tipoTransporte?: string | null;
  contenedorSerieNro?: string | null;
  matriculaCamion?: string | null;
  precinto1?: string | null;
  nombreEstablecimientoDestino: string;
  tipoMovimiento?: string | null;
  observaciones?: string | null;
  paisDestino: string;
  baja?: string | null;
  idLinea?: number | null;
  codigoEnvase?: number | null;
  denominacionMercaderia: string;
  corte: string;
  pallets?: number | null;
  cantidadEnvases?: number | null;
  pesoBruto?: number | null;
  pesoNeto?: number | null;
  nroCertificadoSanitario?: string | null;
  shipping?: string | null;
  loteUsaCanada?: string | null;
  lotesChina?: string | null;
  fechaInicioFaena?: string | null;
  fechaFinFaena?: string | null;
  fechaInicioProduccion?: string | null;
  fechaFinProduccion?: string | null;
  fechaInicioCongelacion?: string | null;
  fechaFinCongelacion?: string | null;
  proceso?: string | null;
  tipo: string;
}